### ISSUE TITLE
E2E Test

### ISSUE THREAD

**Issue by thovid** [rewe-digital/composer#2]
Add a small number of end-2-end tests to demonstrate the features of composer.

**Comment by AndreasKl** [comment]
Think about using sth. lean like https://github.com/square/okhttp/tree/master/mockwebserver instead of wiremock.

**Comment by thovid** [comment]
I'd like to have these end-2-end test somehow separated from our unit tests, so that I can run the unit tests frequently

**Comment by AndreasKl** [comment]
Note: We decided not to start Jetty.

**Comment by AndreasKl** [comment]
Imho as the test runs below a second I assume it is OK for now to have it in the main test suite.

**Comment by thovid** [comment]
Closed via #15
