### ISSUE TITLE
Propagate cache header and if none present add sane defaults

### ISSUE THREAD

**Issue by AndreasKl** [rewe-digital/composer#3]
When a master-template service decides to set Cache-Header he should be able to so. If the service did not set cache header at all, the composer should set sane defaults e.g. no caching. Otherwise things like browser back would return stall data.

**Comment by thovid** [comment]
I am not sure if we want to propagate the cache header of the template to the caller: If the template includes some content, it might be that the content is not cacheable at all.

Imho he cache headers we send to the caller must be some form of minimum of the cache headers of all contributing parts of the page.
