### ISSUE TITLE
Add configurable time-outs for template, proxy and include routes

### ISSUE THREAD

**Issue by AndreasKl** [rewe-digital/composer#8]
Currently there is no facility to define a time-out for proxy and base-template routes, this could be added as part of our routing configuration. The more challenging part is to define time-outs for include routes on a per include base.

Notes:
* Could be implemented as an attribute of the include tag.

**Comment by thovid** [comment]
I'd suggest that we have a default timeout for base templates and a separate timeout for content fragments that can be configured via configuration as well as the option to overwrite these default values via an attribute on the include tag.

**Comment by AndreasKl** [comment]
Agree, as long as the request stack allows a "per request" based timeout; otherwise I would just go with the a configurable overall timeout.

**Comment by thovid** [comment]
Should be possible to configure a timeout per request: `apolloRequest.ttl()`

**Comment by thovid** [comment]
Resolved via #28
