### ISSUE TITLE
Add Caching of template and content responses based on http cache headers

### ISSUE THREAD

**Issue by thovid** [rewe-digital/composer#9]
Composer should recognition cache control headers and cache responses of called services according to their cache control headers in order to minimize internal traffic during request processing.

**Comment by thovid** [comment]
We could use a simple in-memory LRU cache first, and maybe later add some pluggability to support external caches

**Comment by thovid** [comment]
Unfortunately, it seems to be almost impossible to trick apollo into creating a client that uses OkHttpClient's cache support. So, either hack quite a bit around apollo (for example, creating public subclasses for all the package protected modules) or implement a custom caching system using a client decorator... Or drop apollo in favor for something else?

**Comment by thovid** [comment]
We could evaluate https://github.com/httpcache4j/httpcache4j for response caching

**Comment by thovid** [comment]
As httpcache4j does not work well with the asynchronous nature of Composer, I started a spike with Caffeine (see: https://github.com/thovid/composer/tree/http-cache). This works quite well, but the cache caches per instance (from my point of view, this is acceptable for the moment).

**Comment by ben-manes** [comment]
Have you considered using AsyncLoadingCache to memoize the response and avoid racing queries?

**Comment by thovid** [comment]
Thanks for the suggestion, I'll look into it.
